(in-package :fast-arithmetic-tests.avx2)

(fiveam:def-suite avx2-test-suite
    :description "Fast arithmetic AVX2 test suite.")

(fiveam:in-suite avx2-test-suite)

(fiveam:test replicate-float
  (let ((x 1.0))
    (multiple-value-bind (v0 v1 v2 v3 v4 v5 v6 v7)
        (sb-ext:%simd-pack-256-singles (avx2:replicate-float x))
      (fiveam:is (equalp v0 x))
      (fiveam:is (equalp v1 x))
      (fiveam:is (equalp v2 x))
      (fiveam:is (equalp v3 x))
      (fiveam:is (equalp v4 x))
      (fiveam:is (equalp v5 x))
      (fiveam:is (equalp v6 x))
      (fiveam:is (equalp v7 x)))))

(fiveam:test add-single
  (let* ((x 1.0)
        (y 2.0)
        (res (+ x y)))
    (multiple-value-bind (v0 v1 v2 v3 v4 v5 v6 v7)
        (sb-ext:%simd-pack-256-singles (avx2:f8+ (avx2:replicate-float x)
                                                 (avx2:replicate-float y)))
      (fiveam:is (equalp v0 res))
      (fiveam:is (equalp v1 res))
      (fiveam:is (equalp v2 res))
      (fiveam:is (equalp v3 res))
      (fiveam:is (equalp v4 res))
      (fiveam:is (equalp v5 res))
      (fiveam:is (equalp v6 res))
      (fiveam:is (equalp v7 res)))))

(fiveam:test mul-single
  (let* ((x 1.0)
        (y 2.0)
        (res (* x y)))
    (multiple-value-bind (v0 v1 v2 v3 v4 v5 v6 v7)
        (sb-ext:%simd-pack-256-singles (avx2:f8* (avx2:replicate-float x)
                                                 (avx2:replicate-float y)))
      (fiveam:is (equalp v0 res))
      (fiveam:is (equalp v1 res))
      (fiveam:is (equalp v2 res))
      (fiveam:is (equalp v3 res))
      (fiveam:is (equalp v4 res))
      (fiveam:is (equalp v5 res))
      (fiveam:is (equalp v6 res))
      (fiveam:is (equalp v7 res)))))

(fiveam:test sub-single
  (let* ((x 1.0)
        (y 2.0)
        (res (- x y)))
    (multiple-value-bind (v0 v1 v2 v3 v4 v5 v6 v7)
        (sb-ext:%simd-pack-256-singles (avx2:f8- (avx2:replicate-float x)
                                                 (avx2:replicate-float y)))
      (fiveam:is (equalp v0 res))
      (fiveam:is (equalp v1 res))
      (fiveam:is (equalp v2 res))
      (fiveam:is (equalp v3 res))
      (fiveam:is (equalp v4 res))
      (fiveam:is (equalp v5 res))
      (fiveam:is (equalp v6 res))
      (fiveam:is (equalp v7 res)))))

(fiveam:test replicate-double
  (let ((x 1.d0))
    (multiple-value-bind (v0 v1 v2 v3)
        (sb-ext:%simd-pack-256-doubles (avx2:replicate-double x))
      (fiveam:is (equalp v0 x))
      (fiveam:is (equalp v1 x))
      (fiveam:is (equalp v2 x))
      (fiveam:is (equalp v3 x)))))

(fiveam:test add-double
  (let* ((x 1.d0)
        (y 2.d0)
        (res (+ x y)))
    (multiple-value-bind (v0 v1 v2 v3)
        (sb-ext:%simd-pack-256-doubles (avx2:d4+ (avx2:replicate-double x)
                                                 (avx2:replicate-double y)))
      (fiveam:is (equalp v0 res))
      (fiveam:is (equalp v1 res))
      (fiveam:is (equalp v2 res))
      (fiveam:is (equalp v3 res)))))

(fiveam:test mul-double
  (let* ((x 1.d0)
        (y 2.d0)
        (res (* x y)))
    (multiple-value-bind (v0 v1 v2 v3)
        (sb-ext:%simd-pack-256-doubles (avx2:d4* (avx2:replicate-double x)
                                                 (avx2:replicate-double y)))
      (fiveam:is (equalp v0 res))
      (fiveam:is (equalp v1 res))
      (fiveam:is (equalp v2 res))
      (fiveam:is (equalp v3 res)))))

(fiveam:test sub-double
  (let* ((x 1.d0)
        (y 2.d0)
        (res (- x y)))
    (multiple-value-bind (v0 v1 v2 v3)
        (sb-ext:%simd-pack-256-doubles (avx2:d4- (avx2:replicate-double x)
                                                 (avx2:replicate-double y)))
      (fiveam:is (equalp v0 res))
      (fiveam:is (equalp v1 res))
      (fiveam:is (equalp v2 res))
      (fiveam:is (equalp v3 res)))))

(defun run-tests ()
  (fiveam:run! 'avx2-test-suite))
